
enum Types {
    NEWLINE, TAB,

    JMP, PRINTLN,

    VARIABLE, EQUALS, OPAREN, CPAREN, COLON, OPENCURLY, CLOSECURLY, OSQUARE, CSQUARE, QUESTIONMARK,

    INTTYPE, STRINGTYPE, BOOLTYPE, FLOATTYPE,

    INTEGER, STRING, BOOLEAN, FLOAT, INTARR, STRINGARR, BOOLARR, FLOATARR,

    PLUS, MINUS, TIMES, DIVIDE, MODULO, GREATERTHAN, LESSTHAN, AND, OR, NOT, AT, EQUALTO,

    END_OF_INPUT,

    UNKNOWN,

    VARIABLEDECLARATION, ARRAYINIT, TERNARYEXPRESSION, GLUE, ARRAYTYPE, MARKER, ARRAYINDEXASSIGNMENT, STATEMENTLIST,

    ENV, VALUES,
}