
enum Types {
    NEWLINE, TAB,

    JMP, PRINTLN,

    VARIABLE, EQUALS, OPAREN, CPAREN, COLON, OPENCURLY, CLOSECURLY, QUESTIONMARK,

    INTTYPE, STRINGTYPE, BOOLTYPE, FLOATTYPE,

    INTEGER, STRING, BOOLEAN, FLOAT,

    PLUS, MINUS, TIMES, DIVIDE, MODULO, GREATERTHAN, LESSTHAN, AND, OR, NOT, AT, EQUALTO,

    END_OF_INPUT,

    UNKNOWN,
}